/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 47
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_netcdf = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_dimensions_COLON = 4,
  anon_sym_COMMA = 5,
  anon_sym_SEMI = 6,
  anon_sym_EQ = 7,
  aux_sym_dimension_token1 = 8,
  aux_sym_dimension_token2 = 9,
  anon_sym_variables_COLON = 10,
  anon_sym_LPAREN = 11,
  anon_sym_RPAREN = 12,
  sym_dataset_id = 13,
  sym_identifier = 14,
  anon_sym_byte = 15,
  anon_sym_char = 16,
  anon_sym_short = 17,
  anon_sym_int = 18,
  anon_sym_float = 19,
  anon_sym_double = 20,
  anon_sym_ubyte = 21,
  anon_sym_ushort = 22,
  anon_sym_uint = 23,
  anon_sym_int64 = 24,
  anon_sym_uint64 = 25,
  anon_sym_string = 26,
  sym_comment = 27,
  sym_dataset = 28,
  sym_dimensions_section = 29,
  sym_dimension_declarations = 30,
  sym_dimension = 31,
  sym_variables_section = 32,
  sym_variable_declarations = 33,
  sym_variable = 34,
  sym_dimension_spec = 35,
  sym_type = 36,
  aux_sym_dimensions_section_repeat1 = 37,
  aux_sym_dimension_declarations_repeat1 = 38,
  aux_sym_variables_section_repeat1 = 39,
  aux_sym_variable_declarations_repeat1 = 40,
  aux_sym_dimension_spec_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_netcdf] = "netcdf",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_dimensions_COLON] = "dimensions:",
  [anon_sym_COMMA] = ",",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [aux_sym_dimension_token1] = "dimension_token1",
  [aux_sym_dimension_token2] = "dimension_token2",
  [anon_sym_variables_COLON] = "variables:",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_dataset_id] = "dataset_id",
  [sym_identifier] = "identifier",
  [anon_sym_byte] = "byte",
  [anon_sym_char] = "char",
  [anon_sym_short] = "short",
  [anon_sym_int] = "int",
  [anon_sym_float] = "float",
  [anon_sym_double] = "double",
  [anon_sym_ubyte] = "ubyte",
  [anon_sym_ushort] = "ushort",
  [anon_sym_uint] = "uint",
  [anon_sym_int64] = "int64",
  [anon_sym_uint64] = "uint64",
  [anon_sym_string] = "string",
  [sym_comment] = "comment",
  [sym_dataset] = "dataset",
  [sym_dimensions_section] = "dimensions_section",
  [sym_dimension_declarations] = "dimension_declarations",
  [sym_dimension] = "dimension",
  [sym_variables_section] = "variables_section",
  [sym_variable_declarations] = "variable_declarations",
  [sym_variable] = "variable",
  [sym_dimension_spec] = "dimension_spec",
  [sym_type] = "type",
  [aux_sym_dimensions_section_repeat1] = "dimensions_section_repeat1",
  [aux_sym_dimension_declarations_repeat1] = "dimension_declarations_repeat1",
  [aux_sym_variables_section_repeat1] = "variables_section_repeat1",
  [aux_sym_variable_declarations_repeat1] = "variable_declarations_repeat1",
  [aux_sym_dimension_spec_repeat1] = "dimension_spec_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_netcdf] = anon_sym_netcdf,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_dimensions_COLON] = anon_sym_dimensions_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_dimension_token1] = aux_sym_dimension_token1,
  [aux_sym_dimension_token2] = aux_sym_dimension_token2,
  [anon_sym_variables_COLON] = anon_sym_variables_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_dataset_id] = sym_dataset_id,
  [sym_identifier] = sym_identifier,
  [anon_sym_byte] = anon_sym_byte,
  [anon_sym_char] = anon_sym_char,
  [anon_sym_short] = anon_sym_short,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_double] = anon_sym_double,
  [anon_sym_ubyte] = anon_sym_ubyte,
  [anon_sym_ushort] = anon_sym_ushort,
  [anon_sym_uint] = anon_sym_uint,
  [anon_sym_int64] = anon_sym_int64,
  [anon_sym_uint64] = anon_sym_uint64,
  [anon_sym_string] = anon_sym_string,
  [sym_comment] = sym_comment,
  [sym_dataset] = sym_dataset,
  [sym_dimensions_section] = sym_dimensions_section,
  [sym_dimension_declarations] = sym_dimension_declarations,
  [sym_dimension] = sym_dimension,
  [sym_variables_section] = sym_variables_section,
  [sym_variable_declarations] = sym_variable_declarations,
  [sym_variable] = sym_variable,
  [sym_dimension_spec] = sym_dimension_spec,
  [sym_type] = sym_type,
  [aux_sym_dimensions_section_repeat1] = aux_sym_dimensions_section_repeat1,
  [aux_sym_dimension_declarations_repeat1] = aux_sym_dimension_declarations_repeat1,
  [aux_sym_variables_section_repeat1] = aux_sym_variables_section_repeat1,
  [aux_sym_variable_declarations_repeat1] = aux_sym_variable_declarations_repeat1,
  [aux_sym_dimension_spec_repeat1] = aux_sym_dimension_spec_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_netcdf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_dimensions_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_dimension_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dimension_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_variables_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_dataset_id] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_byte] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_char] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_short] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_double] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ubyte] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ushort] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uint64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_dataset] = {
    .visible = true,
    .named = true,
  },
  [sym_dimensions_section] = {
    .visible = true,
    .named = true,
  },
  [sym_dimension_declarations] = {
    .visible = true,
    .named = true,
  },
  [sym_dimension] = {
    .visible = true,
    .named = true,
  },
  [sym_variables_section] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declarations] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_dimension_spec] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_dimensions_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dimension_declarations_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variables_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_declarations_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dimension_spec_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_dimensions = 1,
  field_name = 2,
  field_size = 3,
  field_type = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_dimensions] = "dimensions",
  [field_name] = "name",
  [field_size] = "size",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 0},
    {field_size, 2},
  [3] =
    {field_dimensions, 1},
    {field_name, 0},
  [5] =
    {field_type, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(81);
      ADVANCE_MAP(
        '(', 92,
        ')', 93,
        ',', 86,
        '/', 2,
        ';', 87,
        '=', 88,
        'U', 14,
        'b', 77,
        'c', 36,
        'd', 38,
        'f', 44,
        'i', 52,
        'n', 32,
        's', 35,
        'u', 22,
        'v', 18,
        '{', 83,
        '}', 84,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      END_STATE();
    case 1:
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '\\') ADVANCE(79);
      if (lookahead == 'v') ADVANCE(99);
      if (lookahead == '}') ADVANCE(84);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xffff)) ADVANCE(108);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(121);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(96);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(97);
      END_STATE();
    case 4:
      if (lookahead == '4') ADVANCE(118);
      END_STATE();
    case 5:
      if (lookahead == '4') ADVANCE(119);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(91);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(85);
      END_STATE();
    case 8:
      if (lookahead == 'D') ADVANCE(90);
      END_STATE();
    case 9:
      if (lookahead == 'E') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == 'I') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'I') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'L') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'M') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == 'N') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'T') ADVANCE(9);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(60);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(70);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(61);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'b') ADVANCE(46);
      END_STATE();
    case 21:
      if (lookahead == 'b') ADVANCE(47);
      END_STATE();
    case 22:
      if (lookahead == 'b') ADVANCE(78);
      if (lookahead == 'i') ADVANCE(54);
      if (lookahead == 'n') ADVANCE(45);
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 23:
      if (lookahead == 'c') ADVANCE(24);
      END_STATE();
    case 24:
      if (lookahead == 'd') ADVANCE(33);
      END_STATE();
    case 25:
      if (lookahead == 'd') ADVANCE(90);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(109);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(115);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(114);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 33:
      if (lookahead == 'f') ADVANCE(82);
      END_STATE();
    case 34:
      if (lookahead == 'g') ADVANCE(120);
      END_STATE();
    case 35:
      if (lookahead == 'h') ADVANCE(56);
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 36:
      if (lookahead == 'h') ADVANCE(16);
      END_STATE();
    case 37:
      if (lookahead == 'h') ADVANCE(58);
      END_STATE();
    case 38:
      if (lookahead == 'i') ADVANCE(48);
      if (lookahead == 'o') ADVANCE(76);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(57);
      END_STATE();
    case 43:
      if (lookahead == 'i') ADVANCE(75);
      END_STATE();
    case 44:
      if (lookahead == 'l') ADVANCE(55);
      END_STATE();
    case 45:
      if (lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(28);
      END_STATE();
    case 47:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 48:
      if (lookahead == 'm') ADVANCE(29);
      END_STATE();
    case 49:
      if (lookahead == 'm') ADVANCE(43);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(67);
      END_STATE();
    case 53:
      if (lookahead == 'n') ADVANCE(65);
      END_STATE();
    case 54:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 55:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 56:
      if (lookahead == 'o') ADVANCE(62);
      END_STATE();
    case 57:
      if (lookahead == 'o') ADVANCE(53);
      END_STATE();
    case 58:
      if (lookahead == 'o') ADVANCE(63);
      END_STATE();
    case 59:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 60:
      if (lookahead == 'r') ADVANCE(110);
      END_STATE();
    case 61:
      if (lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 62:
      if (lookahead == 'r') ADVANCE(71);
      END_STATE();
    case 63:
      if (lookahead == 'r') ADVANCE(72);
      END_STATE();
    case 64:
      if (lookahead == 's') ADVANCE(6);
      END_STATE();
    case 65:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 66:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 67:
      if (lookahead == 't') ADVANCE(112);
      END_STATE();
    case 68:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 69:
      if (lookahead == 't') ADVANCE(117);
      END_STATE();
    case 70:
      if (lookahead == 't') ADVANCE(113);
      END_STATE();
    case 71:
      if (lookahead == 't') ADVANCE(111);
      END_STATE();
    case 72:
      if (lookahead == 't') ADVANCE(116);
      END_STATE();
    case 73:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 74:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 75:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 76:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 77:
      if (lookahead == 'y') ADVANCE(73);
      END_STATE();
    case 78:
      if (lookahead == 'y') ADVANCE(74);
      END_STATE();
    case 79:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(107);
      END_STATE();
    case 80:
      if ((' ' <= lookahead && lookahead <= '*') ||
          lookahead == ',' ||
          (':' <= lookahead && lookahead <= '?') ||
          ('[' <= lookahead && lookahead <= '^') ||
          lookahead == '`' ||
          ('{' <= lookahead && lookahead <= '~')) ADVANCE(108);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_netcdf);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_dimensions_COLON);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_dimension_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_dimension_token2);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_variables_COLON);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_dataset_id);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '{') ADVANCE(121);
      if (lookahead != 0) ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_dataset_id);
      if (lookahead == '/') ADVANCE(96);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(97);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_dataset_id);
      if (lookahead == '/') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(97);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_dataset_id);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(91);
      if (lookahead == '\\') ADVANCE(80);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xffff)) ADVANCE(108);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(80);
      if (lookahead == 'a') ADVANCE(105);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xffff)) ADVANCE(108);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(80);
      if (lookahead == 'a') ADVANCE(101);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xffff)) ADVANCE(108);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(80);
      if (lookahead == 'b') ADVANCE(104);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xffff)) ADVANCE(108);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(80);
      if (lookahead == 'e') ADVANCE(106);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xffff)) ADVANCE(108);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(80);
      if (lookahead == 'i') ADVANCE(100);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xffff)) ADVANCE(108);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(80);
      if (lookahead == 'l') ADVANCE(102);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xffff)) ADVANCE(108);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(80);
      if (lookahead == 'r') ADVANCE(103);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xffff)) ADVANCE(108);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(80);
      if (lookahead == 's') ADVANCE(98);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xffff)) ADVANCE(108);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(107);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xffff)) ADVANCE(108);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(80);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xffff)) ADVANCE(108);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_byte);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_char);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_short);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_int);
      if (lookahead == '6') ADVANCE(4);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_double);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_ubyte);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_ushort);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_uint);
      if (lookahead == '6') ADVANCE(5);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_int64);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_uint64);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(121);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_netcdf] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_dimensions_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_dimension_token1] = ACTIONS(1),
    [aux_sym_dimension_token2] = ACTIONS(1),
    [anon_sym_variables_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_byte] = ACTIONS(1),
    [anon_sym_char] = ACTIONS(1),
    [anon_sym_short] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_double] = ACTIONS(1),
    [anon_sym_ubyte] = ACTIONS(1),
    [anon_sym_ushort] = ACTIONS(1),
    [anon_sym_uint] = ACTIONS(1),
    [anon_sym_int64] = ACTIONS(1),
    [anon_sym_uint64] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_dataset] = STATE(44),
    [anon_sym_netcdf] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      sym_type,
    ACTIONS(11), 2,
      anon_sym_int,
      anon_sym_uint,
    STATE(3), 2,
      sym_variable_declarations,
      aux_sym_variables_section_repeat1,
    ACTIONS(9), 10,
      anon_sym_byte,
      anon_sym_char,
      anon_sym_short,
      anon_sym_float,
      anon_sym_double,
      anon_sym_ubyte,
      anon_sym_ushort,
      anon_sym_int64,
      anon_sym_uint64,
      anon_sym_string,
  [30] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      sym_type,
    ACTIONS(11), 2,
      anon_sym_int,
      anon_sym_uint,
    STATE(4), 2,
      sym_variable_declarations,
      aux_sym_variables_section_repeat1,
    ACTIONS(9), 10,
      anon_sym_byte,
      anon_sym_char,
      anon_sym_short,
      anon_sym_float,
      anon_sym_double,
      anon_sym_ubyte,
      anon_sym_ushort,
      anon_sym_int64,
      anon_sym_uint64,
      anon_sym_string,
  [60] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      sym_type,
    ACTIONS(20), 2,
      anon_sym_int,
      anon_sym_uint,
    STATE(4), 2,
      sym_variable_declarations,
      aux_sym_variables_section_repeat1,
    ACTIONS(17), 10,
      anon_sym_byte,
      anon_sym_char,
      anon_sym_short,
      anon_sym_float,
      anon_sym_double,
      anon_sym_ubyte,
      anon_sym_ushort,
      anon_sym_int64,
      anon_sym_uint64,
      anon_sym_string,
  [90] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 2,
      anon_sym_int,
      anon_sym_uint,
    ACTIONS(23), 11,
      anon_sym_RBRACE,
      anon_sym_byte,
      anon_sym_char,
      anon_sym_short,
      anon_sym_float,
      anon_sym_double,
      anon_sym_ubyte,
      anon_sym_ushort,
      anon_sym_int64,
      anon_sym_uint64,
      anon_sym_string,
  [111] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 2,
      anon_sym_int,
      anon_sym_uint,
    ACTIONS(27), 11,
      anon_sym_RBRACE,
      anon_sym_byte,
      anon_sym_char,
      anon_sym_short,
      anon_sym_float,
      anon_sym_double,
      anon_sym_ubyte,
      anon_sym_ushort,
      anon_sym_int64,
      anon_sym_uint64,
      anon_sym_string,
  [132] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      sym_identifier,
    STATE(14), 1,
      sym_dimension,
    ACTIONS(31), 2,
      anon_sym_RBRACE,
      anon_sym_variables_COLON,
    STATE(9), 2,
      sym_dimension_declarations,
      aux_sym_dimensions_section_repeat1,
  [150] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      sym_identifier,
    STATE(14), 1,
      sym_dimension,
    ACTIONS(35), 2,
      anon_sym_RBRACE,
      anon_sym_variables_COLON,
    STATE(8), 2,
      sym_dimension_declarations,
      aux_sym_dimensions_section_repeat1,
  [168] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      sym_identifier,
    STATE(14), 1,
      sym_dimension,
    ACTIONS(40), 2,
      anon_sym_RBRACE,
      anon_sym_variables_COLON,
    STATE(8), 2,
      sym_dimension_declarations,
      aux_sym_dimensions_section_repeat1,
  [186] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_RBRACE,
    ACTIONS(44), 1,
      anon_sym_dimensions_COLON,
    ACTIONS(46), 1,
      anon_sym_variables_COLON,
    STATE(16), 1,
      sym_dimensions_section,
    STATE(39), 1,
      sym_variables_section,
  [205] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      anon_sym_LPAREN,
    STATE(30), 1,
      sym_dimension_spec,
    ACTIONS(48), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [219] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_COMMA,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    STATE(18), 1,
      aux_sym_dimension_declarations_repeat1,
  [232] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_COMMA,
    ACTIONS(58), 1,
      anon_sym_SEMI,
    STATE(20), 1,
      aux_sym_variable_declarations_repeat1,
  [245] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_COMMA,
    ACTIONS(60), 1,
      anon_sym_SEMI,
    STATE(12), 1,
      aux_sym_dimension_declarations_repeat1,
  [258] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      sym_identifier,
    ACTIONS(62), 2,
      anon_sym_RBRACE,
      anon_sym_variables_COLON,
  [269] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_variables_COLON,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      sym_variables_section,
  [282] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_COMMA,
    ACTIONS(71), 1,
      anon_sym_SEMI,
    STATE(17), 1,
      aux_sym_variable_declarations_repeat1,
  [295] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_COMMA,
    ACTIONS(76), 1,
      anon_sym_SEMI,
    STATE(18), 1,
      aux_sym_dimension_declarations_repeat1,
  [308] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(78), 2,
      anon_sym_RBRACE,
      anon_sym_variables_COLON,
  [319] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_COMMA,
    ACTIONS(82), 1,
      anon_sym_SEMI,
    STATE(17), 1,
      aux_sym_variable_declarations_repeat1,
  [332] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_COMMA,
    ACTIONS(86), 1,
      anon_sym_RPAREN,
    STATE(23), 1,
      aux_sym_dimension_spec_repeat1,
  [345] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_COMMA,
    ACTIONS(88), 1,
      anon_sym_RPAREN,
    STATE(21), 1,
      aux_sym_dimension_spec_repeat1,
  [358] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_COMMA,
    ACTIONS(93), 1,
      anon_sym_RPAREN,
    STATE(23), 1,
      aux_sym_dimension_spec_repeat1,
  [371] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_identifier,
    STATE(13), 1,
      sym_variable,
  [381] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      sym_identifier,
    STATE(28), 1,
      sym_dimension,
  [391] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 2,
      aux_sym_dimension_token1,
      aux_sym_dimension_token2,
  [399] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [407] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [415] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_identifier,
    STATE(32), 1,
      sym_variable,
  [425] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [433] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [441] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [449] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [457] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [465] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_LBRACE,
  [472] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
  [479] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
  [486] = 2,
    ACTIONS(115), 1,
      sym_dataset_id,
    ACTIONS(117), 1,
      sym_comment,
  [493] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
  [500] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      sym_identifier,
  [507] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_identifier,
  [514] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_EQ,
  [521] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      sym_identifier,
  [528] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
  [535] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
  [542] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 90,
  [SMALL_STATE(6)] = 111,
  [SMALL_STATE(7)] = 132,
  [SMALL_STATE(8)] = 150,
  [SMALL_STATE(9)] = 168,
  [SMALL_STATE(10)] = 186,
  [SMALL_STATE(11)] = 205,
  [SMALL_STATE(12)] = 219,
  [SMALL_STATE(13)] = 232,
  [SMALL_STATE(14)] = 245,
  [SMALL_STATE(15)] = 258,
  [SMALL_STATE(16)] = 269,
  [SMALL_STATE(17)] = 282,
  [SMALL_STATE(18)] = 295,
  [SMALL_STATE(19)] = 308,
  [SMALL_STATE(20)] = 319,
  [SMALL_STATE(21)] = 332,
  [SMALL_STATE(22)] = 345,
  [SMALL_STATE(23)] = 358,
  [SMALL_STATE(24)] = 371,
  [SMALL_STATE(25)] = 381,
  [SMALL_STATE(26)] = 391,
  [SMALL_STATE(27)] = 399,
  [SMALL_STATE(28)] = 407,
  [SMALL_STATE(29)] = 415,
  [SMALL_STATE(30)] = 425,
  [SMALL_STATE(31)] = 433,
  [SMALL_STATE(32)] = 441,
  [SMALL_STATE(33)] = 449,
  [SMALL_STATE(34)] = 457,
  [SMALL_STATE(35)] = 465,
  [SMALL_STATE(36)] = 472,
  [SMALL_STATE(37)] = 479,
  [SMALL_STATE(38)] = 486,
  [SMALL_STATE(39)] = 493,
  [SMALL_STATE(40)] = 500,
  [SMALL_STATE(41)] = 507,
  [SMALL_STATE(42)] = 514,
  [SMALL_STATE(43)] = 521,
  [SMALL_STATE(44)] = 528,
  [SMALL_STATE(45)] = 535,
  [SMALL_STATE(46)] = 542,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variables_section, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variables_section, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variables_section_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variables_section_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_variables_section_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declarations, 3, 0, 4),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declarations, 3, 0, 4),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declarations, 4, 0, 4),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declarations, 4, 0, 4),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dimensions_section, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dimensions_section_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dimensions_section_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dimensions_section, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 1),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dimension_declarations, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dimension_declarations, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_declarations_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_declarations_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dimension_declarations_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dimension_declarations_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dimension_declarations, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dimension_declarations, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dimension_spec_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dimension_spec_repeat1, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dimension, 3, 0, 2),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, 0, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dimension_spec, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dimension_spec, 4, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dataset, 4, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dataset, 6, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [127] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dataset, 5, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cdl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cdl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
